#!/usr/bin/env python

# binomial
# Jim Bagrow
# Last Modified: 2011-04-06

import sys, os
from numpy import random

if __name__ == '__main__':
    
    # default args:
    n = 2
    p = 0.5
    
    
    args = sys.argv[1:]
    if len(args) == 1: # assume only num_samples
        num_samples = int(sys.argv[1])
    elif len(args) == 2:
        n = int(sys.argv[1])
        num_samples = int(sys.argv[2])
    elif len(args) == 3:
        n = int(sys.argv[1])
        p = float(sys.argv[2])
        num_samples = int(sys.argv[3])
    else:
        sys.exit( "USAGE: %s [n=2] [p=0.5] number_of_samples" % (sys.argv[0]) )
    
    
    sys.stdout.write( "".join("%i\n" % s for s in random.binomial(n,p,num_samples)) )
    sys.stdout.flush() # necessary?
    

