#!/usr/bin/env python

# poisson
# Jim Bagrow
# Last Modified: 2011-04-06

import sys, os
from numpy import random

if __name__ == '__main__':
    
    # default args:
    mean = 1.0
    
    args = sys.argv[1:]
    if len(args) == 1: # assume only num_samples
        num_samples = int(sys.argv[1])
    elif len(args) == 2:
        mean = float(sys.argv[1])
        num_samples = int(sys.argv[2])
    else:
        sys.exit( "USAGE: %s [mean] number_of_samples" % (sys.argv[0]) )
    
    
    sys.stdout.write( "".join("%i\n" % s for s in random.poisson(mean,num_samples)) )
    sys.stdout.flush() # necessary?
    

