#!/usr/bin/env python

# powerlaw
# Jim Bagrow
# Last Modified: 2011-04-06

import sys, os
from random import random
from math import pow

if __name__ == '__main__':
    
    # default args:
    exponent = 3.0
    
    args = sys.argv[1:]
    if len(args) == 1: # assume only num_samples
        num_samples = int(sys.argv[1])
    elif len(args) == 2:
        exponent  = float(sys.argv[1])
        num_samples = int(sys.argv[2])
    else:
        sys.exit( "BAD USAGE: %s [exponent] number_of_samples" % (sys.argv[0]) )
    
    S = [ 1.0 / pow(1-random(),1./(exponent-1)) for x in xrange(num_samples)]
    
    sys.stdout.write("\n".join(map(str,S)))
    sys.stdout.flush() # necessary?

